databases:
  - name: ordo-nomina
    databaseName: live_tracker
    user: pete
    plan: free

services:
  - type: web
    name: ordo-nomina-backend
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ordo-nomina
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default