development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:638cc75fe3d5124adfb40f6fbf4c23ef@scat.redistogo.com:10567
  # channel_prefix: tracker_production
